import Link from "next/link";
import { ArrowUpRight, Plus } from "lucide-react";
import { requireOrganization } from "@/lib/organization";

export default async function OutreachPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const { status: requestedStatus } = await searchParams;
  const statuses = ["draft", "approved", "sent", "failed"] as const;
  const status = statuses.includes(requestedStatus as typeof statuses[number]) ? requestedStatus as typeof statuses[number] : "";
  const { supabase, organization } = await requireOrganization();
  let query = supabase.from("outreach_messages").select("id, lead_id, channel, subject, status, approved_at, sent_at, created_at, leads(name, company)", { count: "exact" }).eq("organization_id", organization.id).is("deleted_at", null).order("created_at", { ascending: false }).limit(100);
  if (status) query = query.eq("status", status);
  const { data, count, error } = await query;
  if (error) throw new Error("Outreach messages could not be loaded.");
  const rows = data ?? [];
  return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm text-violet-300">Outreach workspace</p><h1 className="mt-2 text-3xl font-semibold">Outreach</h1><p className="mt-2 text-sm text-slate-400">Review, edit, approve, and track saved messages.</p></div><Link href="/outreach/new" className="inline-flex h-10 items-center gap-2 rounded-lg bg-violet-600 px-4 text-sm font-semibold hover:bg-violet-500"><Plus className="size-4" />New draft</Link></div>
    <div className="flex flex-wrap gap-2">{["all", ...statuses].map((item) => <Link key={item} href={item === "all" ? "/outreach" : `/outreach?status=${item}`} className={`rounded-full border px-3 py-1.5 text-xs capitalize ${status === item || (!status && item === "all") ? "border-violet-400/30 bg-violet-400/10 text-violet-200" : "border-white/10 text-slate-400"}`}>{item}</Link>)}</div>
    {rows.length ? <div className="overflow-hidden rounded-xl border border-white/10 bg-slate-900/50"><div className="overflow-x-auto"><table className="w-full min-w-[750px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Message</th><th className="px-4 py-3">Lead</th><th className="px-4 py-3">Channel</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Created</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-white/[.07]">{rows.map((item) => { const lead = Array.isArray(item.leads) ? item.leads[0] : item.leads; return <tr key={item.id}><td className="max-w-sm px-5 py-4"><p className="truncate font-medium">{item.subject}</p><p className="mt-1 text-xs text-slate-500">{lead?.name ?? "No lead linked"}{lead?.company ? ` · ${lead.company}` : ""}</p></td><td className="px-4 py-4 text-slate-400">{lead?.company ?? "—"}</td><td className="px-4 py-4 capitalize text-slate-300">{item.channel}</td><td className="px-4 py-4 capitalize">{item.status}</td><td className="px-4 py-4 text-xs text-slate-500">{new Date(item.created_at).toLocaleDateString()}</td><td className="px-5 py-4"><Link href={`/outreach/${item.id}`} className="inline-flex items-center text-xs text-violet-300">Open <ArrowUpRight className="ml-1 size-3" /></Link></td></tr>;})}</tbody></table></div><p className="border-t border-white/10 px-5 py-3 text-xs text-slate-500">{count ?? 0} messages</p></div> : <div className="rounded-xl border border-dashed border-white/15 px-6 py-16 text-center"><h2 className="font-medium">No outreach messages</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-400">Create a draft linked to a real lead. AI generation is available when an OpenAI key is configured; drafts remain under human review.</p><Link href="/outreach/new" className="mt-4 inline-flex text-sm text-violet-300">Create draft <Plus className="ml-1 size-4" /></Link></div>}</div>;
}
