import Link from "next/link";
import { requirePlatformAdmin } from "@/lib/organization";
import { createAdminClient } from "@/lib/supabase/admin";
import { ArchiveOrganizationButton, PermanentlyDeleteOrganization } from "@/components/forms/admin-controls";

export default async function AdminOrganizationsPage() {
  await requirePlatformAdmin();
  const admin = createAdminClient();
  const { data, error } = await admin.from("organizations").select("id, name, slug, industry, created_at, deleted_at, organization_members(count), subscriptions(plan, status, signals_used, signals_total, ai_credits_used, ai_credits_total)").order("created_at", { ascending: false }).limit(200);
  if (error) throw new Error("Platform organizations could not be loaded.");
  return <div><p className="text-sm text-amber-300">Platform administration</p><h2 className="mt-2 text-3xl font-semibold">Organizations</h2><p className="mt-2 text-sm text-slate-400">Workspace memberships, plan, and metered usage from the database.</p><div className="mt-6 space-y-3">{data?.length ? data.map((org) => { const subscription = Array.isArray(org.subscriptions) ? org.subscriptions[0] : org.subscriptions; const memberCount = Array.isArray(org.organization_members) ? org.organization_members[0]?.count ?? 0 : 0; return <article key={org.id} className={`rounded-xl border border-white/10 bg-slate-900/50 p-5 ${org.deleted_at ? "opacity-70" : ""}`}><div className="flex flex-wrap justify-between gap-3"><div><h3 className="font-semibold">{org.name} {org.deleted_at && <span className="ml-2 text-xs text-amber-300">Archived</span>}</h3><p className="mt-1 text-xs text-slate-500">{org.slug} · {org.industry ?? "No industry"} · {org.id}</p></div><p className="text-xs capitalize text-slate-400">{subscription?.plan ?? "No plan"} · {subscription?.status ?? "No subscription"}</p></div><div className="mt-4 flex flex-wrap gap-x-6 gap-y-2 text-xs text-slate-400"><span>{memberCount} member records</span><span>{subscription?.signals_used ?? 0} / {subscription?.signals_total ?? 0} signals</span><span>{subscription?.ai_credits_used ?? 0} / {subscription?.ai_credits_total ?? 0} AI credits</span><span>Created {new Date(org.created_at).toLocaleDateString()}</span></div><div className="mt-4 flex flex-wrap items-start gap-3 border-t border-white/[.07] pt-4">{!org.deleted_at && <ArchiveOrganizationButton organizationId={org.id} />}<details className="w-full"><summary className="cursor-pointer text-xs text-red-300">Permanent deletion controls</summary><PermanentlyDeleteOrganization organizationId={org.id} /></details></div></article>; }) : <p className="rounded-xl border border-white/10 p-8 text-sm text-slate-400">No organizations registered.</p>}</div><Link href="/admin" className="mt-6 inline-block text-sm text-amber-300">Back to platform overview</Link></div>;
}
