import { createAdminClient } from "@/lib/supabase/admin";
import { requirePlatformAdmin } from "@/lib/organization";

export default async function AuditLogsPage({ searchParams }: { searchParams: Promise<{ page?: string }> }) {
  await requirePlatformAdmin();
  const params = await searchParams; const page = Math.max(1, Number(params.page) || 1); const pageSize = 50;
  const admin = createAdminClient();
  const { data, count, error } = await admin.from("audit_logs").select("id, organization_id, actor_id, action, resource_type, resource_id, metadata, created_at", { count: "exact" }).order("created_at", { ascending: false }).range((page - 1) * pageSize, page * pageSize - 1);
  if (error) throw new Error("Audit logs could not be loaded.");
  const totalPages = Math.max(1, Math.ceil((count ?? 0) / pageSize));
  return <div><p className="text-sm text-amber-300">Platform administration</p><h2 className="mt-2 text-3xl font-semibold">Audit logs</h2><p className="mt-2 text-sm text-slate-400">Database-triggered records for administrative and tenant data changes.</p><section className="mt-6 overflow-x-auto rounded-xl border border-white/10 bg-slate-900/50">{data?.length ? <table className="w-full min-w-[850px] text-left text-sm"><thead className="border-b border-white/10 text-xs uppercase tracking-wide text-slate-500"><tr><th className="px-5 py-3">Action</th><th className="px-4 py-3">Resource</th><th className="px-4 py-3">Organization</th><th className="px-4 py-3">Actor</th><th className="px-5 py-3">Time</th></tr></thead><tbody className="divide-y divide-white/[.07]">{data.map((entry) => <tr key={entry.id}><td className="px-5 py-4 font-medium">{entry.action}</td><td className="px-4 py-4"><p>{entry.resource_type}</p><p className="mt-1 font-mono text-xs text-slate-500">{entry.resource_id ?? "—"}</p></td><td className="px-4 py-4 font-mono text-xs text-slate-400">{entry.organization_id ?? "Platform"}</td><td className="px-4 py-4 font-mono text-xs text-slate-400">{entry.actor_id ?? "System or integration"}</td><td className="px-5 py-4 text-xs text-slate-500">{new Date(entry.created_at).toLocaleString()}</td></tr>)}</tbody></table> : <p className="p-8 text-sm text-slate-400">No audit records are available.</p>}<div className="flex justify-between border-t border-white/10 px-5 py-3 text-xs text-slate-500"><span>{count ?? 0} records · Page {page} / {totalPages}</span><div className="flex gap-3">{page > 1 && <a href={`/admin/audit-logs?page=${page - 1}`} className="text-amber-300">Previous</a>}{page < totalPages && <a href={`/admin/audit-logs?page=${page + 1}`} className="text-amber-300">Next</a>}</div></div></section></div>;
}
