import Link from "next/link";
import { notFound } from "next/navigation";
import { deleteTracker, setTrackerStatus } from "@/actions/trackers";
import { ActionButton } from "@/components/forms/action-button";
import { TrackerRerunButton } from "@/components/forms/tracker-rerun-button";
import { requireOrganization } from "@/lib/organization";

export default async function TrackerDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const { supabase, organization } = await requireOrganization();
  const { data: tracker, error } = await supabase.from("keyword_trackers").select("*").eq("organization_id", organization.id).eq("id", id).is("deleted_at", null).maybeSingle();
  if (error) throw new Error("Tracker could not be loaded.");
  if (!tracker) notFound();
  const [{ count, error: signalError }, { data: runs, error: runError }] = await Promise.all([
    supabase.from("intent_signals").select("id", { count: "exact", head: true }).eq("organization_id", organization.id).eq("tracker_id", tracker.id),
    supabase.from("tracker_runs").select("id, status, signals_found, providers_total, providers_completed, created_at, completed_at").eq("organization_id", organization.id).eq("tracker_id", tracker.id).order("created_at", { ascending: false }).limit(10),
  ]);
  if (signalError || runError) throw new Error("Tracker activity could not be loaded.");
  const hasActiveRun = (runs ?? []).some((run) => run.status === "queued" || run.status === "running");
  return <div className="mx-auto max-w-3xl space-y-6"><Link href="/campaigns" className="text-sm text-slate-400 hover:text-white">← Back to trackers</Link><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm text-violet-300">{tracker.status}</p><h1 className="mt-2 text-3xl font-semibold">{tracker.keyword}</h1></div><div className="flex flex-wrap items-center gap-2"><Link href={`/campaigns/${id}/edit`} className="inline-flex h-10 items-center rounded-lg border border-white/10 px-4 text-sm font-medium text-slate-200 hover:bg-white/[.05]">Edit tracker</Link><TrackerRerunButton trackerId={id} disabled={tracker.status !== "active" || hasActiveRun} /><ActionButton variant="secondary" action={setTrackerStatus} fields={{ id, status: tracker.status === "active" ? "paused" : "active" }}>{tracker.status === "active" ? "Pause" : "Resume"}</ActionButton><ActionButton variant="ghost" action={deleteTracker} fields={{ id }}>Archive</ActionButton></div></div>{hasActiveRun && <p role="status" className="rounded-lg border border-amber-300/20 bg-amber-300/[.04] p-3 text-sm text-amber-100">A tracker run is already queued or running. Wait for it to finish before starting another run.</p>}{tracker.status !== "active" && <p role="status" className="rounded-lg border border-amber-300/20 bg-amber-300/[.04] p-3 text-sm text-amber-100">Resume this tracker before starting a run.</p>}<section className="grid gap-3 sm:grid-cols-2"><Detail label="Signals saved" value={count ?? 0} /><Detail label="Alert threshold" value={`${tracker.alert_threshold}%`} /><Detail label="Providers" value={tracker.platforms.join(", ") || "No sources configured"} /><Detail label="Communities" value={tracker.communities.join(", ") || "No communities configured"} /><Detail label="Excluded phrases" value={tracker.negative_keywords.join(", ") || "None"} /></section>
    <section className="rounded-xl border border-white/10 bg-slate-900/50 p-5"><div className="flex items-center justify-between"><div><h2 className="font-semibold">Recent collection runs</h2><p className="mt-1 text-xs text-slate-500">Open any run to inspect provider events and live results.</p></div><span className="text-xs text-slate-500">{runs?.length ?? 0} runs</span></div>{runs?.length ? <ul className="mt-4 divide-y divide-white/[.06]">{runs.map((run) => <li key={run.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><div><Link href={`/campaigns/${id}/runs/${run.id}`} className="text-sm font-medium capitalize text-indigo-200 hover:text-white">{run.status} · {new Date(run.created_at).toLocaleString()}</Link><p className="mt-1 text-xs text-slate-500">{run.providers_completed}/{run.providers_total} providers completed · {run.signals_found} new signals</p></div><Link href={`/campaigns/${id}/runs/${run.id}`} className="text-xs text-slate-400 hover:text-white">View live run →</Link></li>)}</ul> : <p className="mt-4 rounded-lg border border-dashed border-white/10 p-4 text-sm text-slate-400">No collection runs yet. Start a run to verify which providers are actually collecting.</p>}</section>
    <p className="rounded-xl border border-white/10 bg-slate-900/50 p-5 text-sm leading-6 text-slate-400">Collection uses the configured provider integrations and public sources. A run records whether providers connected, scanned records, and saved new signals; empty results are reported honestly.</p></div>;
}

function Detail({ label, value }: { label: string; value: string | number }) { return <div className="rounded-xl border border-white/10 bg-slate-900/50 p-5"><p className="text-xs text-slate-500">{label}</p><p className="mt-2 text-sm font-medium">{value}</p></div>; }
